version: '3.8'

services:
  pihole-app:
    image: 'pihole/pihole:2022.12'
    container_name: 'dns-server-pihole'
    #ports:
    #  - '53:53'
    #  - '53:53/udp'
    #  - '67:67/udp' # Only required if you are using Pi-hole as your DHCP server
    #  - '80:80'
    hostname: 'pihole'
    environment:
      - TZ=America/Maceio
      - CUSTOM_CACHE_SIZE=10000
      - PIHOLE_DNS_=dns-server-unbound
      - WEBPASSWORD=webuserpass
    volumes:
      - '$(pwd)/etc-pihole:/etc/pihole'
      - '$(pwd)/etc-dnsmasq.d:/etc/dnsmasq.d'
      - '$(pwd)/log-pihole/:/var/log/pihole'
    networks:
      - dns-server-net
    depends_on:
      unbounddns-app:
        condition: service_healthy
    restart: always

  unbounddns-app:
    image: 'mvance/unbound:1.16.3'
    container_name: 'dns-server-unbound'
    #ports:
    #  - '53:53'
    #  - '53:53/udp'
    hostname: 'unbounddns'
    volumes:
      - '$(pwd)/etc-unbound:/opt/unbound/etc/unbound'
      - '$(pwd)/log-unbound:/var/log/unbound'
    networks:
      - dns-server-net
    restart: always

networks:
  dns-server-net:
    name: 'dns-server-net'
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/28'
          gateway: 172.18.0.1
