version: '3.8'

services:
  pihole-app:
    image: 'pihole/pihole:2023.02.1'
    container_name: 'dns-server-pihole'
    ports:
      - '53:53'       # DNS Service - TCP
      - '53:53/udp'   # DNS Service - UDP
      # - '67:67/udp' # Only required if you are using Pi-hole as your DHCP server
      # - '80:80'     # HTTP - WebAdmin
    volumes:
      - '$(pwd)/etc_pihole:/etc/pihole'
      - '$(pwd)/etc_dnsmasq.d:/etc/dnsmasq.d'
      - '$(pwd)/log_pihole/:/var/log/pihole'
    environment:
      - TZ=America/Maceio
      - CUSTOM_CACHE_SIZE=10000
      - PIHOLE_DNS_=dns-server-unbound
      - WEBPASSWORD=webuserpass
    hostname: 'pihole'
    networks:
      - dns-server-net
    depends_on:
      unbounddns-app:
        condition: service_healthy
    restart: unless-stopped

  unbounddns-app:
    image: 'mvance/unbound:1.17.0'
    container_name: 'dns-server-unbound'
    #ports:
    # - '53:53'       # DNS Service - TCP
    # - '53:53/udp'   # DNS Service - UDP
    volumes:
      - '$(pwd)/etc_unbound:/opt/unbound/etc/unbound'
      - '$(pwd)/log_unbound:/var/log/unbound'
    hostname: 'unbounddns'
    networks:
      - dns-server-net
    restart: unless-stopped

networks:
  dns-server-net:
    name: 'dns-server-net'
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/28'
